homeassistant:
  # Name of the location where Home Assistant is running
  name: Ich

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_altitude

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City

  customize: !include customize.yaml

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 172.17.0.1
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
    - type: homeassistant

  whitelist_external_dirs:
    - '/config/www/media/'
    - '/config/www/media/camera-01/'
    - '/config/www/media/camera-02/'

  # Load packages
  packages: !include_dir_named components/packages

hacs:
  token: !secret hacs_token
