title: Ich

resources: !include lovelace/resources.yaml

views:

  - !include lovelace/home.yaml
  - !include lovelace/server.yaml
  - !include lovelace/mqtt.yaml
  - !include lovelace/computervision.yaml
  - !include lovelace/openvino.yaml
