# Home Location
# https://www.google.com/maps
home_latitude: 20.7087217
home_longitude: -103.3935931

# Elevation
home_altitude: 1820

# HTTP API Password
http_api_password: parques2urbanos

# HACS
hacs_token: 0000000000000000000000000000000000000000

# Services
services_glances_url: http://172.17.0.1:61208
services_glances_api: 172.17.0.1
services_grafana_url: http://172.17.0.1:3000
services_grafana_openfaas: http://172.17.0.1:3000/d/9_Uy9ucZz/original-open-faas-dashboard?orgId=1&refresh=1s&from=now-5m&to=now
services_netdata_url: http://172.17.0.1:19999
services_nodered_url: http://172.17.0.1:1880
services_nodered_dashboard_url: http://172.17.0.1:1880/ui
services_motioneye_url: http://172.17.0.1:8765
services_plex_url: http://172.17.0.1:32400/web/index.html
services_portainer_url: http://172.17.0.1:9000
services_windy_url: https://embed.windy.com/embed2.html?lat=23.564&lon=-102.305&zoom=5&level=surface&overlay=rain&menu=&message=true&marker=&calendar=12&pressure=&type=map&location=coordinates&detail=&detailLat=20.724&detailLon=-103.385&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1

# Components Sensor Dark Sky
# https://www.home-assistant.io/components/sensor.darksky/
# Secret Key: https://darksky.net/dev/register
darksky_secret_key: 00000000000000000000000000000000

# Components Sensor World Air Quality Index
# https://www.home-assistant.io/components/sensor.waqi/
# API Token: http://aqicn.org/data-platform/token/#/
aqicn_api_token: 0000000000000000000000000000000000000000

# Components RESTful Sensor
# https://www.home-assistant.io/components/rest/
rest_resource: http://httpbin.org/ip

# Components Camera FFmpeg
ffmpeg_camera_01: tcp://172.17.0.1:5001
ffmpeg_camera_02: tcp://172.17.0.1:5002

# Components Camera Generic MJPEG IP
mjpeg_camera_01: http://172.17.0.1:9081/?action=stream
mjpeg_camera_01_still_image: http://192.168.1.83:9081/?action=snapshot
mjpeg_camera_02: http://172.17.0.1:9081/?action=stream
mjpeg_camera_02_still_image: http://192.168.1.83:9081/?action=snapshot

# Components Camera Generic
generic_camera_01: rtsp://172.17.0.1/v02
generic_camera_01_still_image: http://172.17.0.1/cgi-bin/snapshot.cgi?loginuse=admin&loginpas=admin
generic_camera_01_username: admin
generic_camera_01_password: admin

generic_camera_02: rtsp://172.17.0.1/v02
generic_camera_02_still_image: http://172.17.0.1/cgi-bin/snapshot.cgi?loginuse=admin&loginpas=admin
generic_camera_02_username: admin
generic_camera_02_password: admin

camera_01_ip_address: 172.17.0.1
camera_02_ip_address: 172.17.0.1

rest_edgex_random_boolean_device: http://192.168.1.91:48082/api/v1/device/c0c8fa4d-383f-44c0-b4aa-45183cdeda15/command/6bfd3b5b-f09f-403f-882b-58d543f4bf8f
rest_edgex_random_integer_device: http://192.168.1.91:48082/api/v1/device/bc3bf935-a089-4486-9009-2f6a3af03155/command/400bbcac-283e-4a71-8a83-4f7cfae92abe
rest_edgex_random_unsignedinteger_device: http://192.168.1.91:48082/api/v1/device/70c2d93b-3b45-45b4-8bd6-d68fc97091ee/command/81b81589-fb2d-409a-9580-0a4fe9aefc9f

application_restricted_zone_notifier_cpp: "http://172.17.0.1:8126/container/application-restricted-zone-notifier-cpp"
application_restricted_zone_notifier_python: "http://172.17.0.1:8126/container/application-restricted-zone-notifier-python"
application_shopper_gaze_monitor_cpp: "http://172.17.0.1:8126/container/application-shopper-gaze-monitor-cpp"
application_shopper_mood_monitor_cpp: "http://172.17.0.1:8126/container/application-shopper-mood-monitor-cpp"
application_parking_lot_counter_cpp: "http://172.17.0.1:8126/container/application-parking-lot-counter-cpp"
application_object_size_detector_cpp: "http://172.17.0.1:8126/container/application-object-size-detector-cpp"
application_safety_gear_detector_cpp: "http://172.17.0.1:8126/container/application-safety-gear-detector-cpp"

application_face_detection_and_classification: "http://172.17.0.1:8126/container/application-face-detection-and-classification"
application_mers_face_detection_and_classification: "http://172.17.0.1:8126/container/application-mers-face-detection-and-classification"

application_face_detection_and_classification_publish_mqtt: "http://172.17.0.1:8126/container/application-face-detection-and-classification-publish-mqtt"
application_mers_face_detection_and_classification_publish_mqtt: "http://172.17.0.1:8126/container/application-mers-face-detection-and-classification-publish-mqtt"

application_face_detection_multichannel: "http://172.17.0.1:8126/container/application-face-detection-multichannel"
application_mers_face_detection_multichannel: "http://172.17.0.1:8126/container/application-mers-face-detection-multichannel"

application_vehicle_detection_publish_mqtt: "http://172.17.0.1:8126/container/application-vehicle-detection-publish-mqtt"
application_mers_vehicle_detection_publish_mqtt: "http://172.17.0.1:8126/container/application-mers-vehicle-detection-publish-mqtt"

# ESPHome
esphome_wifi_ssid: "IoT"
esphome_wifi_password: "12345678"

# Wio Link 01
wio_link_01_motion:
wio_link_01_dust:
wio_link_01_sound:

# Telegram
telegram_token:
telegram_chat_id_one:
