version: '3.7'
services:

  mjpeg-streamer:
    build:
      context: ./mjpeg-streamer/
      dockerfile: Dockerfile.mjpeg-streamer
      args:
        - VIDEO_DEVICE=${VIDEO_DEVICE:-/dev/video0}
        - SERVER_TCP_PORT=${SERVER_TCP_PORT:-8080}
    image: xe1gyq/mjpeg-streamer
    container_name: ich-mjpeg-streamer
    privileged: true
    environment:
      - TZ=America/Mexico_City
      - VIDEO_DEVICE=${VIDEO_DEVICE:-/dev/video0}
      - SERVER_TCP_PORT=${SERVER_TCP_PORT:-8080}
    network_mode: host
    ports:
      - 8080:8080
    devices:
      - /dev

  opencv:
    build:
      context: ./opencv/
      dockerfile: Dockerfile.opencv
    image: xe1gyq/opencv
    container_name: ich-opencv
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev

  openvino:
    build:
      context: ./openvino/
      dockerfile: Dockerfile.openvino
    image: xe1gyq/openvino
    container_name: ich-openvino
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev

  openvino-2018r5:
    build:
      context: ./openvino-2018r5/
      dockerfile: Dockerfile.openvino-2018r5
    image: xe1gyq/openvino-2018r5
    container_name: ich-openvino-2018r5
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev
