version: '3.7'
services:

  mjpeg-streamer:
    build:
      context: ./mjpeg-streamer/
      dockerfile: Dockerfile.mjpeg-streamer
      args:
        - VIDEO_DEVICE=${VIDEO_DEVICE:-/dev/video0}
        - SERVER_TCP_PORT=${SERVER_TCP_PORT:-9081}
    image: xe1gyq/mjpeg-streamer
    container_name: ich-mjpeg-streamer
    privileged: true
    environment:
      - TZ=America/Mexico_City
      - VIDEO_DEVICE=${VIDEO_DEVICE:-/dev/video0}
      - SERVER_TCP_PORT=${SERVER_TCP_PORT:-9081}
    network_mode: host
    ports:
      - 8080:8080
    devices:
      - /dev

  opencv:
    build:
      context: ./opencv/
      dockerfile: Dockerfile.opencv
    image: xe1gyq/opencv
    container_name: ich-opencv
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev

  openvino:
    build:
      context: ./openvino/
      dockerfile: Dockerfile.openvino
    image: xe1gyq/openvino
    container_name: ich-openvino
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev

  openvino-official:
    build:
      context: ./openvino-official/
      dockerfile: Dockerfile.openvino-official
    image: xe1gyq/openvino-official
    container_name: ich-openvino-official
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev

  filehash:
    build:
      context: ./filehash/
      dockerfile: Dockerfile.filehash
    image: xe1gyq/filehash
    container_name: ich-filehash
    privileged: true
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev
    volumes:
      - ../media/:/media/

  jupyter:
    build:
      context: ./jupyter/
      dockerfile: Dockerfile.jupyter
    image: xe1gyq/jupyter
    container_name: ich-jupyter
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev

  deepstack:
    image: deepquestai/deepstack
    container_name: ich-deepstack
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    devices:
      - /dev
