platform: rest
resource: !secret application_vehicle_detection_publish_mqtt
name: Application Vehicle Detection Publish MQTT
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
