platform: rest
resource: !secret application_mers_face_detection_and_classification_publish_mqtt
name: Application MeRS Face Detection and Classification Publish MQTT
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
