platform: rest
resource: !secret application_dlrs_restricted_zone_notifier_python
name: Application DLRS Restricted Zone Notifier Python
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
