platform: rest
resource: !secret application_dlrs_multicamera_multiperson_demo_python
name: Application DLRS MultiCamera MultiPerson Demo Python
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
