platform: rest
resource: !secret application_restricted_zone_notifier_cpp
name: Application Restricted Zone Notifier CPP
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
