platform: rest
resource: !secret application_parking_lot_counter_cpp
name: Application Parking Lot Counter CPP
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
