platform: rest
resource: !secret application_object_size_detector_cpp
name: Application Object Size Detector CPP
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
