alias: Application Face Detection Multichannel
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.application_face_detection_multichannel
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/fdm_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: camera.record
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/fdm_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
