alias: Application MultiCamera MultiPerson Demo Python
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.application_multicamera_multiperson_demo_python
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/mcmpd_python_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: camera.record
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/mcmpd_python_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
