alias: Application MeRS Face Detection and Classification
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.application_mers_face_detection_and_classification
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/mfdac_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: camera.record
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/mfdac_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
