alias: Application Vehicle Detection Publish MQTT
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.vehicle_detection_publish_mqtt
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/mvdpm_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: camera.record
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/applications/mvdpm_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
