alias: Frontyard Light On Night
initial_state: 'true'
trigger:
  platform: state
  entity_id: binary_sensor.frontyard_motion
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.frontyard_light
      state: 'off'
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
action:
  service: light.turn_on
  entity_id: light.frontyard_light
