alias: Frontyard Light Off Night
initial_state: 'true'
trigger:
  platform: state
  entity_id: binary_sensor.frontyard_motion
  to: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.frontyard_light
      state: 'on'
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
action:
  service: light.turn_off
  entity_id: light.frontyard_light
