alias: 'Telegram Ich Project Bot Ping'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/ping'
action:
  - service: notify.telegram_ich_project_bot
    data:
      message: 'pong'
