substitutions:
  main_name: "ESPHome Hello World"

esphome:
  name: "esphomehelloworld"
  platform: ESP8266
  board: nodemcuv2

<<: !include common/main.yaml

switch:
  - platform: gpio
    name: ${main_name} Pin D4
    pin: D4
    inverted: True

binary_sensor:
  - !include common/binary_sensors/status.yaml

sensor:
  - !include common/sensors/uptime.yaml
  - !include common/sensors/wifi-signal.yaml

text_sensor:
  - platform: version
    name: ${main_name} Version
