alias: Xolopet 0005 60
initial_state: 'true'
trigger:
  - platform: numeric_state
    entity_id: sensor.xolopet_0005_percentage
    below: 60
    for:
      hours: 0
      minutes: 5
      seconds: 0
action:
  - service: notify.mobile_app_iphone_de_gerardo
    data_template:
      message: >
        {{ trigger.to_state.name }} {{ trigger.to_state.state }}
  - service: notify.mobile_app_vtr_l09
    data_template:
      message: >
        {{ trigger.to_state.name }} {{ trigger.to_state.state }}
  - service: notify.mobile_app_moto_g_5_plus
    data_template:
      message: >
        {{ trigger.to_state.name }} {{ trigger.to_state.state }}
