# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Application Parking Lot Counter CPP In
state_topic: "parking/counter"
value_template: "{{ value_json.TOTAL_IN }}"
unit_of_measurement: 'Count'
