# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Application Face Detection and Classification Publish MQTT Timestamp
state_topic: "application/fdacpm/demo"
value_template: '{{ value_json.timestamp }}'
