# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Application MeRS Vehicle Detection Publish MQTT Timestamp
state_topic: "MQTTExamples"
value_template: "{{ value_json.timestamp }}"
unit_of_measurement: 'Count'
