# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Application Shopper Mood Monitor CPP Sad
state_topic: "retail/traffic"
value_template: "{{ value_json.sad }}"
unit_of_measurement: 'Count'
