# https://www.home-assistant.io/integrations/binary_sensor.mqtt/

platform: mqtt
name: Application Interactive Face Recognition Demo Python
state_topic: "Face_recognition_demo"
value_template: '{{ value_json.Alert }}'
payload_on: "True"
payload_off: "False"
device_class: motion
force_update: true
