# https://www.home-assistant.io/integrations/binary_sensor.mqtt/

platform: mqtt
name: Application MeRS Vehicle Detection Publish MQTT
state_topic: ""
value_template: '{{ value_json.objects.label_id }}'
payload_on: "0"
payload_off: "1"
device_class: motion
force_update: true
